#!/bin/bash
# File              : edit-config
# License           : MIT
# Author            : Steven Agustinus <steven87.ags@gmail.com>
# Date              : 15.06.2021
# Last Modified Date: 15.06.2021
# Last Modified By  : Steven Agustinus <steven87.ags@gmail.com>
# edit-config
# Copyright (c) 2021 Steven Agustinus <steven87.ags@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

E="st -e vim"
H=$HOME
C=$HOME/.config

declare -a CFGS=(
"VIM         ==>     $H/.vimrc"
"XMONAD      ==>     $H/.xmonad/xmonad.hs"
"XMOBAR1     ==>     $C/xmobar/xmobarrc"
"XMOBAR2     ==>     $C/xmobar/xmobarrc2"
"QUTEBROWSER ==>     $C/qutebrowser/config.py"
"KITTY       ==>     $C/kitty/kitty.conf"
"NEOFETCH    ==>     $C/neofetch/config.conf"
"RANGER      ==>     $C/ranger/ranger/rc.conf"
"MPV         ==>     $C/mpv/mplayer-input.conf"
"DUNST       ==>     $C/dunst/dunstrc"
"CONKY       ==>     $C/conky/conky.conf"
"ZSH         ==>     $H/.zshrc"
)



LCFGS=$(printf '%s\n' "${CFGS[@]}" | awk '{print $1}' | dmenu -l 20 -c -bw 2 -i -p "Edit Config: ") || exit
SCFGS=$(printf '%s\n' "${CFGS[@]}" | grep -i "$LCFGS" | awk '{print $NF}')


$E $SCFGS

