#!/bin/bash
# File              : screen-recorder
# License           : MIT
# Author            : Steven Agustinus <steven87.ags@gmail.com>
# Date              : 11.06.2021
# Last Modified Date: 11.06.2021
# Last Modified By  : Steven Agustinus <steven87.ags@gmail.com>
# record.sh
# Copyright (c) 2021 Steven Agustinus <steven87.ags@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

NAME=$(printf '%s' 'Screen-Record-'\ "$(date +'%d-%m-%y:%H:%M:%S').mp4")
SAVE="/home/steven/screen-record"

declare -a ACTIONS=(
"SCREEN-1" 
"SCREEN-2" 
"STOP"
)

OPTIONS=$(printf '%s\n' "${ACTIONS[@]}"  |  awk '{print $1}'| dmenu -l 4 -c -bw 2 -i -p "RECORD : " ) || exit 
NOTIF="dunstify -t 2000 Screen-Recording \n$OPTIONS"

function S1(){
$NOTIF 
ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 "${SAVE}/${NAME}"
#ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264rgb -crf 0 -preset veryfast "${SAVE}/${NAME}"
}

function S2(){
$NOTIF
ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0+1920,0 "${SAVE}/${NAME}"
#ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0+1920,0 -c:v libx264rgb -crf 0 -preset veryfast "${NAME}"
}


if [[ "$OPTIONS" == 'SCREEN-1' ]] ; then
    S1    
elif [[ "$OPTIONS" == 'SCREEN-2' ]] ; then
    S2
#elif [[ "$OPTIONS" == 'STOP' ]] ; then
#      killall ffmpeg 
else killall ffmpeg && dunstify -t 2000 'Stop Recording' 
fi


