#!/bin/bash
# File              : screen-recorder
# License           : MIT
# Author            : Steven Agustinus <steven87.ags@gmail.com>
# Date              : 11.06.2021
# Last Modified Date: 21.07.2021
# Last Modified By  : Steven Agustinus <steven87.ags@gmail.com>
# record.sh
# Copyright (c) 2021 Steven Agustinus <steven87.ags@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

NAME=$(printf '%s' 'Screen-record-'"$(date +'%d-%m-%y:%H:%M:%S').mp4")
SAVE="$HOME/screen-records"

declare -a ACTIONS=(
"🖥 SCREEN-1 - VIDEO_ONLY 🔇" 
"🖥 SCREEN-2 - VIDEO_ONLY 🔇" 
"🖥 SCREEN-1 - WITH AUDIO 🔊" 
"🖥 SCREEN-2 - WITH AUDIO 🔊" 
"❌ STOP RECORDING"
)

OPTIONS=$(printf '%s\n' "${ACTIONS[@]}"  |  dmenu -l 5 -c -bw 2 -i -p "🎬 RECORD : " ) || exit 
NOTIF="dunstify -t 2000 Screen-Recording "
LATEST=$(ls -t "$SAVE" | head -n 1)

#RECORD SCREEN-1 VIDEO ONLY
function S1(){
$NOTIF "\n${ACTIONS[0]}"
#dunstify -t 2000 Screen-Recording "\n🖥 SCREEN-1"  
##whithout anullsrc audio filter / without Inject Null Audio
#ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -pix_fmt yuv420p -preset veryfast "${SAVE}/${NAME}" \

# With Anullsrc Audio Filter
ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 \
    -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -c:a aac \
    -shortest -pix_fmt yuv420p -preset veryfast "${SAVE}/${NAME}"
# Lossless Record
#ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264rgb -crf 0 -preset veryfast "${SAVE}/${NAME}"
}

#RECORD SCREEN-2 VIDEO ONLY
function S2(){
$NOTIF "\n${ACTIONS[1]}"
dunstify -t 2000 Screen-Recording "\n🖥 SCREEN-1"  
#ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0+1920,0 -pix_fmt yuv420p  -preset veryfast "${SAVE}/${NAME}" \

# With Anullsrc Audio Filter
ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0 \
    -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -c:a aac \
    -shortest -pix_fmt yuv420p -preset veryfast "${SAVE}/${NAME}"
#ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0+1920,0 -c:v libx264rgb -crf 0 -preset veryfast "${NAME}"
}

# SCREEN-1 VIDEO WITH AUDIO
function S1AV(){
$NOTIF "\n${ACTIONS[2]}"
ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0+0,0 \
    -f alsa -ac 2 -i default -pix_fmt yuv420p -preset veryfast "${SAVE}/${NAME}"
}

# SCREEN-2 VIDEO WITH AUDIO
function S2AV(){
$NOTIF "\n${ACTIONS[3]}"
ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0+0,0 \
    -f alsa -ac 2 -i default -pix_fmt yuv420p -preset veryfast "${SAVE}/${NAME}"
}

# ADD/INJECT NULL AUDIO
#function S3() {
#ffmpeg -y -i "${SAVE}/${LATEST}" -f lavfi -i anullsrc -c:v copy  -c:a aac -shortest "${SAVE}/${NAME}" 
#}


if [[ "$OPTIONS" == "${ACTIONS[0]}" ]] ; then
    S1
elif [[ "$OPTIONS" == "${ACTIONS[1]}" ]] ; then
    S2
elif [[ "$OPTIONS" == "${ACTIONS[4]}"  ]] ; then
    killall ffmpeg 
#    dunstify -t 2000 "❌ STOP RECORDING"   
    $NOTIF "\n\n${ACTIONS[4]}"
fi





   # sleep 1
   # S3 
   # sleep 1
#CHECKING & DELETE ORIGINAL FILE
   # for i in "${SAVE[@]}/*" ;
   # do
   #     x=($i)
   #     z=${x[-2]} 
   #     kill ffmpeg
   #     sleep 2
   #     rm $z
   # done 
